application.secrets.mail# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6cf531a375c177ecfe66416be62c87af20d623024ff9b9fc57532576574d02f47a88f4d0048523ffa1f78e528f8f3325c1c88283f615c7114d1b13bb0bf6711
  mail: "edutech.reply.only@gmail.com"
  pass: "Kebin0102"

test:
  secret_key_base: ed9e2491d560c64d5c0768df793ed75c2e6835bff0d2dec26c276d9d1cd1bf764b2deb9c56c5b17c434593926c0b72562afda0827fb48592fa320cd0e4a4bf5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mail: "edutech.reply.only@gmail.com"
  pass: "Kebin0102"